shiro:
   loginUrl: /login
   successUrl: /index
   unauthorizedUrl: /static/errors/403.html
   cacheManagerConfigFile: classpath:shiro/shiro-cache.xml
   hashAlgorithmName: SHA-1
   hashIterations: 1024
   filterChainDefinitionMap:
      /api/account/login: anon
      /api/account/logout: anon
      /api/account/current: anon
      /api/**: authc